# Configuration file for bike-sharing project

data:
  train: "data/raw/train.csv"
  test: "data/raw/test.csv"
  sample_submission: "data/raw/sampleSubmission.csv"
  processed_train: "data/processed/train_processed.csv"
  processed_test: "results/submission.csv"

logging:
  log_file: "logs/model_training.log"

models:
  ridge:
    alpha: 1.0
  random_forest:
    n_estimators: 100
    max_depth: 10
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
